name: 同步外刊到Obsidian

on:
  # 在同步上游仓库工作流完成后运行
  workflow_run:
    workflows: ["同步上游仓库"]
    types:
      - completed
  # 允许手动触发
  workflow_dispatch:

jobs:
  sync-to-cos:
    runs-on: ubuntu-latest
    # 只有当触发的工作流成功完成时才运行
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    
    steps:
      # 检出当前仓库代码（使用稀疏检出策略，只检出必要的目录结构）
      - name: 检出当前仓库
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          sparse-checkout: |
            01_economist
            02_new_yorker
            04_atlantic
            05_wired
          sparse-checkout-cone-mode: true
      
      # 安装AWS CLI
      - name: 安装AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2
      
      # 直接配置AWS凭证（用于访问腾讯云COS）
      - name: 配置AWS凭证
        run: |
          mkdir -p ~/.aws
          cat > ~/.aws/credentials << EOF
          [default]
          aws_access_key_id = ${{ secrets.COS_SECRET_ID }}
          aws_secret_access_key = ${{ secrets.COS_SECRET_KEY }}
          EOF
          
          cat > ~/.aws/config << EOF
          [default]
          region = ${{ secrets.COS_REGION }}
          s3 =
            addressing_style = virtual
            endpoint_url = https://cos.${{ secrets.COS_REGION }}.myqcloud.com
          EOF
      
      # 获取当前日期
      - name: 获取当前日期
        id: date
        run: echo "date=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT
      
      # 查找最新的经济学人文件
      - name: 查找最新的经济学人文件
        id: economist
        run: |
          LATEST_ECONOMIST_DIR=$(find ./01_economist -type d -name "te_*" | sort -r | head -n 1)
          echo "latest_dir=$LATEST_ECONOMIST_DIR" >> $GITHUB_OUTPUT
          echo "找到最新的经济学人目录: $LATEST_ECONOMIST_DIR"
      
      # 查找最新的纽约客文件
      - name: 查找最新的纽约客文件
        id: newyorker
        run: |
          LATEST_NEWYORKER_DIR=$(find ./02_new_yorker -type d -name "*" -not -path "*/\.*" | sort -r | head -n 1)
          echo "latest_dir=$LATEST_NEWYORKER_DIR" >> $GITHUB_OUTPUT
          echo "找到最新的纽约客目录: $LATEST_NEWYORKER_DIR"
      
      # 同步经济学人到COS
      - name: 同步经济学人到COS
        if: steps.economist.outputs.latest_dir != ''
        run: |
          aws configure set default.s3.addressing_style virtual
          aws s3 sync ${{ steps.economist.outputs.latest_dir }} s3://${{ secrets.COS_BUCKET }}/obisidian-1302893975/2.外刊/经济学人/${{ steps.date.outputs.date }}/ --no-verify-ssl
          echo "已同步经济学人到COS"
      
      # 同步纽约客到COS
      - name: 同步纽约客到COS
        if: steps.newyorker.outputs.latest_dir != ''
        run: |
          aws s3 sync ${{ steps.newyorker.outputs.latest_dir }} s3://${{ secrets.COS_BUCKET }}/obisidian-1302893975/2.外刊/纽约客/${{ steps.date.outputs.date }}/ --no-verify-ssl
          echo "已同步纽约客到COS"
      
      # 同步The Atlantic到COS（如果有更新）
      - name: 同步The Atlantic到COS
        run: |
          LATEST_ATLANTIC_DIR=$(find ./04_atlantic -type d -name "*" -not -path "*/\.*" | sort -r | head -n 1)
          if [ -n "$LATEST_ATLANTIC_DIR" ]; then
            aws s3 sync $LATEST_ATLANTIC_DIR s3://${{ secrets.COS_BUCKET }}/obisidian-1302893975/2.外刊/大西洋月刊/${{ steps.date.outputs.date }}/ --no-verify-ssl
            echo "已同步The Atlantic到COS"
          else
            echo "未找到The Atlantic目录"
          fi
      
      # 同步Wired到COS（如果有更新）
      - name: 同步Wired到COS
        run: |
          LATEST_WIRED_DIR=$(find ./05_wired -type d -name "*" -not -path "*/\.*" | sort -r | head -n 1)
          if [ -n "$LATEST_WIRED_DIR" ]; then
            aws s3 sync $LATEST_WIRED_DIR s3://${{ secrets.COS_BUCKET }}/obisidian-1302893975/2.外刊/连线杂志/${{ steps.date.outputs.date }}/ --no-verify-ssl
            echo "已同步Wired到COS"
          else
            echo "未找到Wired目录"
          fi
